# Netlify deploy configuration
[build.environment]
  NODE_VERSION = "20.17.0"

[build]
  command = "ng build --configuration production"
  publish = "dist/ShowerGlass/browser"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "https://dushcabs.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "https://dushcabs.onrender.com/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
